version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: mutantdb
      MYSQL_ROOT_PASSWORD: C/.5&kb4u^80
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql

  app:
    build: .
    container_name: sprinboot
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mutantdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: C/.5&kb4u^80
    depends_on:
      - mysql
    networks:
      - springboot-mysql

volumes:
  mysql-data:

networks:
  springboot-mysql:
    driver: bridge